/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesp;

import Proyecto.GrafoLista;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Alexandra
 */
public class Ventana1 extends javax.swing.JFrame {
    static GrafoLista grafo;
    /**
     * Creates new form Ventana1
     */
    public Ventana1(GrafoLista grafo) {
        this.grafo = grafo;
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                grafo.Writetxt(grafo);
                
                System.exit(0);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        InicioSesion = new javax.swing.JButton();
        Registrarse = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        MostrarGrafo = new javax.swing.JButton();
        SalirVent1 = new javax.swing.JButton();
        FondoVent1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioSesion.setBackground(new java.awt.Color(255, 255, 153));
        InicioSesion.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        InicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        InicioSesion.setText("Iniciar sesión");
        InicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 140, 30));

        Registrarse.setBackground(new java.awt.Color(255, 255, 153));
        Registrarse.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        Registrarse.setForeground(new java.awt.Color(0, 0, 0));
        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 140, 30));

        Eliminar.setBackground(new java.awt.Color(255, 255, 153));
        Eliminar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(0, 0, 0));
        Eliminar.setText("Eliminar usuario");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 140, 30));

        MostrarGrafo.setBackground(new java.awt.Color(255, 255, 153));
        MostrarGrafo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        MostrarGrafo.setForeground(new java.awt.Color(0, 0, 0));
        MostrarGrafo.setText("Mostrar grafo");
        MostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 140, 40));

        SalirVent1.setBackground(new java.awt.Color(255, 153, 51));
        SalirVent1.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        SalirVent1.setForeground(new java.awt.Color(0, 0, 0));
        SalirVent1.setText("Salir");
        SalirVent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVent1ActionPerformed(evt);
            }
        });
        getContentPane().add(SalirVent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        FondoVent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen1/FondoVent1.jpg"))); // NOI18N
        getContentPane().add(FondoVent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
 * Este botón hace que al presionarlo dirija al usuario hacia la Ventana2
 * Se ejecuta cuando el usuario hace clic en el botón de inicio sesión.
 * @param evt Este parámetro no utiliza este método.
 * 
 */

    private void InicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioSesionActionPerformed
       Ventana2 v2=new Ventana2(this);
    }//GEN-LAST:event_InicioSesionActionPerformed
/**
 * Este método se ejecuta cuando el usuario hace clic en el botón de salida en la Ventana1
 * Escribe el estado actual del grafo en un archivo de texto y luego cierra la ventana
 * @param evt Este parámetro no se utiliza en este método
 * 
 */

    private void SalirVent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVent1ActionPerformed
        grafo.Writetxt(grafo);
        this.dispose();
    }//GEN-LAST:event_SalirVent1ActionPerformed
/**
 * Este botón hace que al presionarlo dirija al usuario hacia la Ventana3
 * Se ejecuta cuando el usuario hace clic en el botón de Registrarse
 * @param evt Este parámetro no utiliza este método.
 * 
 */

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        Ventana3 v3=new Ventana3(this);
    }//GEN-LAST:event_RegistrarseActionPerformed
/**
 * Este botón hace que al presionarlo diriga al usuaio hacia la Ventana4
 * Se ejecuta cuando el usuario hace clic en el boton de Eliminar Usuario.
 * @param evt Este parámetro no utiliza este método.
 * 
 */

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        Ventana4 v4=new Ventana4(this);
    }//GEN-LAST:event_EliminarActionPerformed
/**
 * Este botón hace que al presionarlo el usuario pueda ver el grafo graficamente
 * Se ejecuta cuando el usuario hace clic en el boton de Mostrar grafo.
 * @param evt Este parámetro no utiliza este método.
 * 
 */

    private void MostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGrafoActionPerformed
        // TODO add your handling code here:
        grafo.ShowGraph();
    }//GEN-LAST:event_MostrarGrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel FondoVent1;
    private javax.swing.JButton InicioSesion;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton Registrarse;
    private javax.swing.JButton SalirVent1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
