/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesp;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandra
 */
public class Ventana4 extends javax.swing.JFrame {
        public static Ventana1 v1;
        public static String UsuarioInput ;
    /**
     * Creates new form Ventana4
     */
    public Ventana4(Ventana1 v1) {
        initComponents();
        this.v1=v1;
        UsuarioInput="";
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                Ventana1.grafo.Writetxt(Ventana1.grafo);
                
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Atrasvent4 = new javax.swing.JButton();
        SalirVent4 = new javax.swing.JButton();
        Ingresar = new javax.swing.JLabel();
        UsuarioEliminar = new javax.swing.JTextField();
        OkEliminar = new javax.swing.JButton();
        FondoV4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        Atrasvent4.setBackground(new java.awt.Color(255, 153, 51));
        Atrasvent4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        Atrasvent4.setForeground(new java.awt.Color(0, 0, 0));
        Atrasvent4.setText("Atrás");
        Atrasvent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atrasvent4ActionPerformed(evt);
            }
        });
        getContentPane().add(Atrasvent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        SalirVent4.setBackground(new java.awt.Color(255, 153, 51));
        SalirVent4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        SalirVent4.setForeground(new java.awt.Color(0, 0, 0));
        SalirVent4.setText("Salir");
        SalirVent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVent4ActionPerformed(evt);
            }
        });
        getContentPane().add(SalirVent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        Ingresar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        Ingresar.setText("Ingrese el nombre de usuario que desee eliminar");
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        UsuarioEliminar.setBackground(new java.awt.Color(255, 255, 153));
        UsuarioEliminar.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(UsuarioEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 20));

        OkEliminar.setBackground(new java.awt.Color(255, 255, 153));
        OkEliminar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        OkEliminar.setForeground(new java.awt.Color(0, 0, 0));
        OkEliminar.setText("Ok");
        OkEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(OkEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        FondoV4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen1/FondoV4.jpg"))); // NOI18N
        getContentPane().add(FondoV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Atrasvent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atrasvent4ActionPerformed
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_Atrasvent4ActionPerformed
/**
 * AL presionar el botón se cerrará el programa
 * @param evt 
 */

    private void SalirVent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVent4ActionPerformed
        Ventana1.grafo.Writetxt(Ventana1.grafo);
        System.exit(0);
    }//GEN-LAST:event_SalirVent4ActionPerformed

    private void UsuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioEliminarActionPerformed
/**
 * Este método recupera el texto del campo UsuarioEliminar, 
 * elimina el usuario correspondiente del grafo, 
 * borra el texto del campo UsuarioEliminar y muestra un mensaje indicando que el usuario ha sido eliminado.
 *
 * @param evt 
 * @author Alexandra Padrón
 */

    private void OkEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkEliminarActionPerformed
        
        
        
        UsuarioInput= UsuarioEliminar.getText();
        
        Ventana1.grafo.DeleteUsuario(UsuarioInput);
        UsuarioEliminar.setText("");
        
        
    }//GEN-LAST:event_OkEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana4(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atrasvent4;
    private javax.swing.JLabel FondoV4;
    private javax.swing.JLabel Ingresar;
    private javax.swing.JButton OkEliminar;
    private javax.swing.JButton SalirVent4;
    private javax.swing.JTextField UsuarioEliminar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
