/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesp;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandra
 */
public class Ventana3 extends javax.swing.JFrame {
        public static Ventana1 v1;
        
        
    
    /**
     * Creates new form Ventana3
     */
    public Ventana3(Ventana1 v1) {
        initComponents();
       
        this.v1=v1;
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        for (int i = 0; i < Ventana1.grafo.getNumVerts(); i++) {
             Sugerencias.addItem(Ventana1.grafo.getTabAdy()[i].getUsuario());
        }
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                Ventana1.grafo.Writetxt(Ventana1.grafo);
                
                System.exit(0);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SalirVent3 = new javax.swing.JButton();
        AtrasVent3 = new javax.swing.JButton();
        UsuarioNuevo = new javax.swing.JTextField();
        REGISTRO = new javax.swing.JButton();
        Sugerencia = new javax.swing.JLabel();
        SeguirA = new javax.swing.JTextField();
        UsuarioSeguir = new javax.swing.JLabel();
        SEGUIR = new javax.swing.JButton();
        Sugerencias = new javax.swing.JComboBox<>();
        IngreseUsuario = new javax.swing.JLabel();
        FondoVent3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        SalirVent3.setBackground(new java.awt.Color(255, 153, 51));
        SalirVent3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        SalirVent3.setForeground(new java.awt.Color(0, 0, 0));
        SalirVent3.setText("Salir");
        SalirVent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVent3ActionPerformed(evt);
            }
        });
        getContentPane().add(SalirVent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        AtrasVent3.setBackground(new java.awt.Color(255, 153, 51));
        AtrasVent3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        AtrasVent3.setForeground(new java.awt.Color(0, 0, 0));
        AtrasVent3.setText("Atrás");
        AtrasVent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasVent3ActionPerformed(evt);
            }
        });
        getContentPane().add(AtrasVent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        UsuarioNuevo.setBackground(new java.awt.Color(255, 255, 153));
        UsuarioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(UsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, -1));

        REGISTRO.setBackground(new java.awt.Color(255, 255, 153));
        REGISTRO.setForeground(new java.awt.Color(0, 0, 0));
        REGISTRO.setText("Ok");
        REGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTROActionPerformed(evt);
            }
        });
        getContentPane().add(REGISTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        Sugerencia.setBackground(new java.awt.Color(0, 0, 0));
        Sugerencia.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        Sugerencia.setText("Sugerencias de seguidores");
        getContentPane().add(Sugerencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 20));

        SeguirA.setBackground(new java.awt.Color(255, 255, 153));
        SeguirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguirAActionPerformed(evt);
            }
        });
        getContentPane().add(SeguirA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 130, -1));

        UsuarioSeguir.setBackground(new java.awt.Color(0, 0, 0));
        UsuarioSeguir.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        UsuarioSeguir.setText("Ingrese el nombre del usuario al que desea seguir");
        getContentPane().add(UsuarioSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 350, -1));

        SEGUIR.setBackground(new java.awt.Color(255, 255, 153));
        SEGUIR.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        SEGUIR.setForeground(new java.awt.Color(0, 0, 0));
        SEGUIR.setText("Seguir");
        SEGUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEGUIRActionPerformed(evt);
            }
        });
        getContentPane().add(SEGUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        Sugerencias.setBackground(new java.awt.Color(255, 255, 153));
        Sugerencias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SugerenciasItemStateChanged(evt);
            }
        });
        Sugerencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SugerenciasActionPerformed(evt);
            }
        });
        getContentPane().add(Sugerencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, -1));

        IngreseUsuario.setBackground(new java.awt.Color(0, 0, 0));
        IngreseUsuario.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        IngreseUsuario.setText("Ingrese su nombre de usuario para registrarse");
        getContentPane().add(IngreseUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 380, -1));

        FondoVent3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen1/Fondo3.jpg"))); // NOI18N
        getContentPane().add(FondoVent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Escribe el estado actual del grafo en un archivo de texto y luego cierra la aplicación.
 *
 * @param Este parámetro no se utiliza en el método.
 * 
 */

    private void SalirVent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVent3ActionPerformed
        Ventana1.grafo.Writetxt(Ventana1.grafo);
        System.exit(0);
    }//GEN-LAST:event_SalirVent3ActionPerformed
/**
 * Oculta la Ventana3 y muestra la Ventana1.
 *
 * @param  Este parámetro no se utiliza en el método.
 * @author Alexandra Padrón
 */

    private void AtrasVent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasVent3ActionPerformed
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_AtrasVent3ActionPerformed
/**
 * Este método Recupera el texto del campo UsuarioNuevo y lo valida.
 * Si el nombre de usuario es válido, crea un nuevo usuario en el grafo
 * @param evt El evento de acción. Este parámetro no se utiliza en el método.
 */

    private void REGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTROActionPerformed
          
          String UsuarioInput = "";
          UsuarioInput= UsuarioNuevo.getText();
          //UsuarioNuevo.setText("");
        if (Funciones.Validar(UsuarioInput)){
              boolean bool =Ventana1.grafo.NewUsuario(UsuarioInput);
              if (bool){
                  UsuarioNuevo.setEditable(false);
                  JOptionPane.showMessageDialog(null, "Usuario registrado con exito!");
                  }else{
              UsuarioNuevo.setText("");
              UsuarioNuevo.setEditable(true);
              }
              
              
        }
        
      
        
        
        
    }//GEN-LAST:event_REGISTROActionPerformed

    private void UsuarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UsuarioNuevoActionPerformed

    private void SugerenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SugerenciasActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_SugerenciasActionPerformed
/**
 * Aquí se rupera el usuario seleccionado de Sugerencias y busca su correspondencia en el grafo.
 * Si encuentra una correspondencia establece el texto de SeguirA en el usuario seleccionado.
 *
 * @param evt  Este parámetro no se utiliza en el método.
 */

    private void SugerenciasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SugerenciasItemStateChanged
        // TODO add your handling code here:
        String Uselected =(String) Sugerencias.getSelectedItem();
        for (int i = 0; i < Ventana1.grafo.getNumVerts(); i++) {
            if (Uselected == Ventana1.grafo.getTabAdy()[i].getUsuario()){
                SeguirA.setText(Uselected);
            }
        }
    }//GEN-LAST:event_SugerenciasItemStateChanged
/**
 * Se recupera el texto de los campos UsuarioNuevo y SeguirA, y crea un nuevo arco en el grafo entre estos dos usuarios.
 * Luego borra el texto del campo SeguirA y muestra un mensaje indicando que ahora sigue al usuario seleccionado.
 *
 * @param evt El evento de acción. Este parámetro no se utiliza en el método
 */

    private void SEGUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEGUIRActionPerformed
        // TODO add your handling code here:
        String UsuarioInput = "";
        UsuarioInput= UsuarioNuevo.getText();
        String SeguirA_ = SeguirA.getText();
        boolean bool =Ventana1.grafo.nuevoArco(UsuarioInput,SeguirA_ );
       
        if (bool){
            JOptionPane.showMessageDialog(null, "A partir de ahora sigue a:  "+SeguirA_  + "\nSi desea seguir a alguien más, seleccionelo en la lista!");
            
        }
       SeguirA.setText("");
       
    }//GEN-LAST:event_SEGUIRActionPerformed

    private void SeguirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguirAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguirAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasVent3;
    private javax.swing.JLabel FondoVent3;
    private javax.swing.JLabel IngreseUsuario;
    private javax.swing.JButton REGISTRO;
    private javax.swing.JButton SEGUIR;
    private javax.swing.JButton SalirVent3;
    private javax.swing.JTextField SeguirA;
    private javax.swing.JLabel Sugerencia;
    private javax.swing.JComboBox<String> Sugerencias;
    private javax.swing.JTextField UsuarioNuevo;
    private javax.swing.JLabel UsuarioSeguir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
